openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
    description: Test server
paths:
  /login:
    $ref: './paths/users.yaml#/Login'
  /registration:
    $ref: './paths/users.yaml#/Registration'
  /logout:
    $ref: './paths/users.yaml#/Logout'
  /refresh:
    $ref: './paths/users.yaml#/Refresh'
  /forget_password:
    $ref: './paths/users.yaml#/ForgetPassword'
  /recover_password:
    $ref: './paths/users.yaml#/RecoverPassword'