version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-container
    ports:
      - '9001:9001'
    env_file: .env
    volumes:
      - minio_data:/Users/silchenko/server-data
  
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server

  server:
    build: .
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - minio
      - redis

volumes:
  minio_data: